### ISSUE TITLE
not working on 1.19.2 spigot

### ISSUE THREAD

**Issue by GeunSam2** [herby2212/FakePlayers#11] opened 2022-08-06 17:21 UTC
I'm using this plug-in really well. However, I found out that the recently updated version of spigot 1.19.2 does not work as a bug like the following, so I am reporting it.

```
[16:57:50] [Server thread/WARN]: java.lang.IllegalAccessException: class de.Herbystar.FakePlayers.PlayerListHandler.NMS_PlayerListHandler cannot access a member of class net.minecraft.server.players.PlayerList with modifiers "private final"
[16:57:50] [Server thread/WARN]:        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
[16:57:50] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
[16:57:50] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
[16:57:50] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:423)
[16:57:50] [Server thread/WARN]:        at de.Herbystar.FakePlayers.PlayerListHandler.NMS_PlayerListHandler.setOnlinePlayers(NMS_PlayerListHandler.java:115)
[16:57:50] [Server thread/WARN]:        at de.Herbystar.FakePlayers.Main.setFakePlayers(Main.java:94)
[16:57:50] [Server thread/WARN]:        at de.Herbystar.FakePlayers.Main.onEnable(Main.java:77)
[16:57:50] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:57:50] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[16:57:50] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[16:57:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523)
[16:57:50] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437)
[16:57:50] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584)
[16:57:50] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403)
[16:57:50] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255)
[16:57:50] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968)
[16:57:50] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[16:57:50] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:57:50] [Server thread/ERROR]: Error occurred while enabling FakePlayers v2.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "de.Herbystar.FakePlayers.PlayerListHandler.NMS_PlayerListHandler.list" is null
        at de.Herbystar.FakePlayers.PlayerListHandler.NMS_PlayerListHandler.addCustomOnlinePlayer(NMS_PlayerListHandler.java:161) ~[?:?]
        at de.Herbystar.FakePlayers.Main.setFakePlayers(Main.java:96) ~[?:?]
        at de.Herbystar.FakePlayers.Main.onEnable(Main.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3564-Spigot-584b459-ec2b5d4]
        at java.lang.Thread.run(Thread.java:833) [?:?]

```

**Comment by herby2212** [comment] 2022-08-06 17:24
Thanks for the report. It seems they changed there class property. I will take a look into it.

**Comment by GeunSam2** [comment] 2022-08-06 17:32
Thank you so much for making a good plug-in. I really love this!

**Comment by herby2212** [comment] 2022-08-21 16:34
Fixed with release [2.7](https://github.com/herby2212/FakePlayers/releases/tag/2.7).

**Closed by herby2212** 2022-08-21 16:34 UTC
Labels: bug

**Comment by Stage4000** [comment] 2022-08-25 19:22
I feel you may have prematurely closed these threads relating to 1.19.2

Version: 2.7
Setup: Bungeecord over Spigot

[14:18:05] [Server thread/INFO]: Stage4000 issued server command: /fakeplayers create [redacted]
[14:18:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fakeplayers' in plugin FakePlayers v2.7
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1944) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1909) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "de.Herbystar.FakePlayers.PlayerListHandler.PlayerListHandler.addCustomOnlinePlayer(String)" because "de.Herbystar.FakePlayers.Main.instance.playerListHandler" is null
at de.Herbystar.FakePlayers.Commands.onCommand(Commands.java:25) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 23 more

**Comment by herby2212** [comment] 2022-08-25 19:54
> I feel you may have prematurely closed these threads relating to 1.19.2
> 
> Version: 2.7 Setup: Bungeecord over Spigot
> 
> [14:18:05] [Server thread/INFO]: Stage4000 issued server command: /fakeplayers create [redacted] [14:18:05] [Server thread/ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'fakeplayers' in plugin FakePlayers v2.7 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:?] at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1944) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1909) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3575-Spigot-450dcaa-370eece] at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.NullPointerException: Cannot invoke "de.Herbystar.FakePlayers.PlayerListHandler.PlayerListHandler.addCustomOnlinePlayer(String)" because "de.Herbystar.FakePlayers.Main.instance.playerListHandler" is null at de.Herbystar.FakePlayers.Commands.onCommand(Commands.java:25) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?] ... 23 more

Greetings,
is you want to have faked Players on a BungeeCord network in the server list you can use CBMFC.

If you still want to use FakePlayers on individual servers inside a BungeeCord network I could take a look at it, but would need a full console log from you.

**Comment by Stage4000** [comment] 2022-08-25 20:05
I appreciate the alternate plugin recommendation and am looking into it as we speek.
as far as logs go: that is all it gives me, in console and in logs it always gives me '23 more' at the end, if you want to make a NFOservers account and send me your email address associated with it I can give you full console and FTP access to a test environment for bungee over spigot. You can send your associated email to _mail_ or via Discord _discordHandle_ if you want to proceed. Please kindly delete this comment to protect my personal contact information upon reading it. <3

**Comment by herby2212** [comment] 2022-08-25 20:15
> I appreciate the alternate plugin recommendation and am looking into it as we speek. as far as logs go: that is all it gives me, in console and in logs it always gives me '23 more' at the end, if you want to make a NFOservers account and send me your email address associated with it I can give you full console and FTP access to a test environment for bungee over spigot. You can send your associated email to _mail_ or via Discord _discordHandle_ if you want to proceed. Please kindly delete this comment to protect my personal contact information upon reading it. <3

Hey your server should have a latest.log file in your logs folder that would be enough. No access to the server required ;)
Also feel free to visit my discord channel there we can discuss this topic in a seperate thread. Your personal informations got removed.
